apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: web-app
  template:
    metadata: 
      name: web-app
      labels:
        app: web-app
    spec:
      containers:
        - name: web-image
          image: web
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80