apiVersion: v1
kind: Pod
metadata:
  name: web-app
  labels:
    app: db
spec:
  containers:
    - name: nginx-app
      image: web
      imagePullPolicy: IfNotPresent
      ports:
        - containerPort: 80

        //docker push 
        // docker build -t web .
        // docker run -p 8080:80 web

        // kubectl apply -f deploy.yaml
        // kubectl apply -f nodeport.yaml
        // minikube service node-port-service


        

        
